name: Update QA Website

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Convert Excel to JSON
        run: |
          python .github/scripts/excel_to_json.py
          echo "Contenu du dossier ./ :"
          ls -la ./
          echo "Contenu du fichier JSON :"
          cat ./qa_data.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Build website
        run: |
          npm run build
          echo "Contenu du dossier dist :"
          ls -la dist/
          echo "Vérification du JSON dans dist :"
          cat dist/qa_data.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist